### ISSUE TITLE
请问下载链接失败，http status400怎么解决

### ISSUE THREAD

**Issue by ImAlien** [ZJU-Rule/ZJU-Rule#1]
我原本就是clash链接，转换后的链接下载不了
windows10 clash版本0.19.8

**Comment by Mythologyli** [comment]
试一下在浏览器可以打开这个链接吗？
https://sub.zjurule.xyz/version

**Comment by ImAlien** [comment]
你给的链接没用呀
![image](https://user-images.githubusercontent.com/35003534/155084516-df17d683-f2ca-4e80-bf92-9a5add08a1fa.png)
网址不是这个吗https://zjurule.xyz/

**Comment by Mythologyli** [comment]
看来你的网络环境可以访问到 subconverter api
那应该是 subconverter 无法从你的订阅链接中获取节点
方便的话可以 CC98 私信交流吗？

**Comment by ImAlien** [comment]
不知道什么情况，现在好像可以了

**Comment by Mythologyli** [comment]
那有可能是网络环境波动，之前 subconverter 没从订阅链接中获取到节点

**Comment by ImAlien** [comment]
可能是吧 ，rvpn和clash之前有冲突，麻烦了
