### ISSUE TITLE
导入安卓版clash时下载失败

### ISSUE THREAD

**Issue by fishfishfishfishfish** [ZJU-Rule/ZJU-Rule#2]
您好！我把生成的链接导入安卓版clash时下载失败，不知道哪里操作错误了。感谢！

**Comment by fishfishfishfishfish** [comment]
报错如下
![18bc9a19e704a15235b2c509bb3904d](https://user-images.githubusercontent.com/17529439/155239512-66aebda8-7421-47cb-9e77-696a76f18083.jpg)

**Comment by Mythologyli** [comment]
在 PC 端导入时正常吗？
可以尝试在安卓端用流量获取一下

**Comment by fishfishfishfishfish** [comment]
PC端导入正常，用流量获取的意思是不要用wifi吗

**Comment by fishfishfishfishfish** [comment]
用流量还是下载失败

**Comment by Mythologyli** [comment]
推测还是链接的问题，可以 CC98 站内私信交流吗？

**Comment by fishfishfishfishfish** [comment]
好的，你就是帖子的楼主对吧

**Comment by Mythologyli** [comment]
> 好的，你就是帖子的楼主对吧

是的

**Comment by Mythologyli** [comment]
原先安卓端 Clash 版本老旧，使用 cfa-2.5.4-premium-arm64-v8a-release.apk 正常
