### ISSUE TITLE
TWO more ZJU-Rules

### ISSUE THREAD

**Issue by ljcppp** [ZJU-Rule/ZJU-Rule#4]
http://icsr.wiki/ and https://zjusec.com/ can only be opened on the intranet of Zhejiang University.
Please add rule 
- DOMAIN-SUFFIX,icsr.wiki,✔ ZJU内网
- DOMAIN-SUFFIX,zjusec.com,✔ ZJU内网
in ZJU-Rule.

**Comment by Mythologyli** [comment]
ICSR WIKI and ZJU School-Bus have been added to ZJU.list.
You can resync profile in Clash to check it.
Thanks for your contribution.
