### ISSUE TITLE
找不到奈菲节点，没法看奈菲

### ISSUE THREAD

**Issue by brane-theory** [ZJU-Rule/ZJU-Rule#6]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/61408487/155841344-c729d926-cf2d-4464-ac69-595283ef9a6c.png">
咋办？

**Comment by Mythologyli** [comment]
![image](https://user-images.githubusercontent.com/15955880/155841879-362fb975-2f10-4cc3-b248-9b759041ddca.png)

不用管下面的奈非节点，在上面的奈非视频中选择节点选择，就会继承节点选择中的选项
