### ISSUE TITLE
谷歌学术403错误

### ISSUE THREAD

**Issue by StrongJeremy** [ZJU-Rule/ZJU-Rule#7]
不挂clash可以正常进入谷歌学术，挂了之后谷歌学术403错误（403. That’s an error.Your client does not have permission to get URL / from this server.）。
但谷歌可以正常进。这个是梯子的问题嘛？

**Comment by Mythologyli** [comment]
- DOMAIN-SUFFIX,googlescholar.com,🚀 节点选择

谷歌学术走节点选择中的选择。我这里使用没有问题，请尝试更换节点选择中的节点
